### ISSUE TITLE
Broken "postinstall"

### ISSUE THREAD

**Issue by zimbatm** [moretea/yarn2nix#12]
If the main `package.json` contains a "postinstall" instruction, it's possible that it won't work depending on the assumption that are being made.

The issue is that the source code of the project is not available so if the postinstall step is to convert the sourcecode from typescript to javascript for example it won't work.

**Comment by moretea** [comment]
We could add a flag (e.g. `override.my_pkg.mutableSource=true;`) that will create an environment for that package that is writeable, instead of linking it from the nix store.

**Comment by zimbatm** [comment]
Maybe I should say that it's for the main `package.json`, not for dependencies.

I think in that case the source should be copied over into the build context.

**Comment by moretea** [comment]
OK. Did you encounter an actual case that did not work properly? I'd like to start adding some tests.

**Comment by zimbatm** [comment]
One of the project I wanted to convert to yarn2nix has something like that:

```json
{
  "name": "somethingsomething",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "npm rebuild node-sass"
  },
  "devDependencies": {
    "node-sass": "^3.8.0",
  }
}
```

Presumably this has been added as a workaround for non-deterministic builds.

**Comment by moretea** [comment]
:scream:
Did you find a solution yet?
I guess we should make it possible for `yarn2nix` to override those impurities. The the easiest solution would be to (monkey) patch yarn, generating a "custom" package introduces way more complexity.

**Comment by zimbatm** [comment]
In theory it should be possible to use `lib.importJSON`, pass it through a transforming function and write the package.json back into the /nix/store. In practice I think I'll try to bludgeon the developers, or try to understand why they are doing this.

**Comment by moretea** [comment]
If you'd generate a new `package.json`, yarn will get upset. The `packacke.json` files from dependencies are stored _inside_ the tar.gz files that we'll put in the offline cache. We probably have to regenerate the SHA's in the yarn.lock file if we want to be able to override the content in there. Hence my suggestion to just (monkey) patch yarn to modify the content of `packages.json` on the fly.

**Comment by Pauan** [comment]
I just ran into this issue.

I'm trying to create a Nix derivation for [Koka](https://github.com/koka-lang/koka). There is a [postinstall](https://github.com/Pauan/koka/blob/fac9020716971751c26711c3d07923e475fda6e6/package.json#L40) script which compiles the Haskell source code into a binary.

This all works fine with `npm` and `yarn`, but it fails with `yarn2nix` because `yarn2nix` doesn't run any `postinstall` scripts, therefore the Koka binary is never generated.

And unfortunately Koka relies upon the npm packages `jake` and `madoko` to do the compilation, so I *have* to use `yarn2nix` (or an alternative like `node2nix`)

In my particular use case, I don't need the *dependencies* to run `postinstall`, I only need the top level package (i.e. Koka) to run `postinstall`

However, even if `yarn2nix` supported `postinstall`, that still might not be enough, because Koka writes the binary into a sub-directory, and Nix is supposed to be immutable. :frowning_face:

**Comment by Pauan** [comment]
I was able to find a workaround.

In my `default.nix` I use `buildYarnPackage` to fetch the `node_modules` packages:

```nix
let
  name = "koka-0.8.0-dev";

  src = fetchFromGitHub {
    owner = "Pauan";
    repo = "koka";
    rev = "fac9020716971751c26711c3d07923e475fda6e6";
    sha256 = "0l5ikd6ppxp8gfxrj0rm2amwyp14pymba2qxhgsi0r6qmk8ydjxi";
  };
in
  stdenv.mkDerivation {
    inherit name src;

    nodePackages = buildYarnPackage {
      inherit name src;
      packageJson = "${src}/package.json";
      yarnLock = "${src}/yarn.lock";
    };

    builder = ./builder.sh;

    buildInputs = [ yarn ];
  }
```

Then I created this `builder.sh` script:

```bash
source $stdenv/setup

cp --recursive "$src/." "."

ln --symbolic "$nodePackages/node_modules" "node_modules"

HOME="$TMPDIR"

yarn run postinstall

mkdir "$out"
mkdir "$out/bin"

cp "out/release/$name" "$out/bin/koka"
```

This copies the `$src` into the current directory, and it makes a symbolic link to the `node_modules` folder (which is created by `buildYarnPackage`)

Now it can run the `postinstall` script which builds the Koka binary, then it copies the Koka binary into `$out`

**Comment by moretea** [comment]
Awesome!

The problem is still indeed that npm just assumes that `node_modules` is writeable. In that case, a tool such as `node2nix` might be more suitable, given that it's basically a re-implementation of yarn/npm, and could handle custom behaviour.

**Comment by qknight** [comment]
@moretea compiling our monitoring frontend using `node-sass` fails using `nix-build` but works using `nix-shell` and therefore sass seems to be doing something statefully. 

now i wonder if that can be fixed in `node-sass` or if that is a npm specific problem which can't be fixed in `node-sass` itself.

```
cat package.json | grep sass
    "bootstrap-sass": "*",
    "ember-cli-sass": "*",
    "node-sass": "*"
```

```
du -a | grep sass/vend
3048    ./node_modules/node-sass/vendor/linux-x64-48/binding.node  (ELF binary)
3052    ./node_modules/node-sass/vendor/linux-x64-48
3056    ./node_modules/node-sass/vendor
```
# nix-build

```
nix-build release.nix 
these derivations will be built:
  /nix/store/7ikfx3gvskna4i11phi6na39hi9rwvlv-nixcloud-stalker-frontend.drv
building path(s) ‘/nix/store/a719pym8gwix74mpsd9q1gnkdf0vsiya-nixcloud-stalker-frontend’
unpacking sources
unpacking source archive /nix/store/x4g60i7z9br4gilsq5g8vy73s62vyyb8-stalker-frontend
source root is stalker-frontend
patching sources
configuring
building

> nixcloud-stalker-frontend@0.0.0 build /tmp/nix-build-nixcloud-stalker-frontend.drv-0/stalker-frontend
> ember build

ENOENT: no such file or directory, scandir '/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/vendor'
Error: ENOENT: no such file or directory, scandir '/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at Object.getInstalledBinaries (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/nix/store/lq9jlm5zngkas7jh28pdrz0jz6ib3mdc-nixcloud-stalker-frontend-modules-0.0.0/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 4.9.30
npm ERR! argv "/nix/store/20g9mwm84z0wi32f2bfl4r2fws7n18ra-nodejs-6.11.4/bin/node" "/nix/store/20g9mwm84z0wi32f2bfl4r2fws7n18ra-nodejs-6.11.4/bin/npm" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nixcloud-stalker-frontend@0.0.0 build: `ember build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nixcloud-stalker-frontend@0.0.0 build script 'ember build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nixcloud-stalker-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nixcloud-stalker-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nixcloud-stalker-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nix-build-nixcloud-stalker-frontend.drv-0/stalker-frontend/npm-debug.log
builder for ‘/nix/store/7ikfx3gvskna4i11phi6na39hi9rwvlv-nixcloud-stalker-frontend.drv’ failed with exit code 1
error: build of ‘/nix/store/7ikfx3gvskna4i11phi6na39hi9rwvlv-nixcloud-stalker-frontend.drv’ failed
```
see also https://github.com/davezuko/react-redux-starter-kit/issues/791

**Comment by uvNikita** [comment]
@qknight we have the same issue with node-sass (vendor directory not found error). I was wondering if you've found any workaround for it?

**Comment by qknight** [comment]
@uvNikita no we didn't IIRC

**Comment by nightkr** [comment]
Don't have the time to detail how right now, but we have node-sass working at https://github.com/Etimo/photo-garden/blob/master/default.nix (though it builds really slowly).

**Comment by uvNikita** [comment]
@teozkr thanks for the link! I tried to add these lines to our default.nix, but that didn't solve the issue -- libsass was still not building or downloading:

```
pkgConfig.node-gyp.buildInputs = [ nodejs.python ];
yarnPreBuild =
  ''
    export npm_config_nodedir=${nodejs}
    export SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=1
  '';

# Strip debugging references for the sake of the closure size
pkgConfig.node-sass.postInstall =
  ''
    find -iname binding.node -exec strip -s {} +
  '';
```

I found another repo however and they added `yarn--offline run build` to `postInstall`: https://github.com/input-output-hk/daedalus/blob/af1d39028a6de5d26095e835035c0778a8163c75/yarn2nix.nix#L111-L114

Now libsass is building but takes a very long time to do so.

**Comment by uvNikita** [comment]
And it seems like it rebuilds it pretty much on any change in default.nix.

**Comment by jfraudeau** [comment]
Out of topic but regarding the node-sass.
I managed to get significantly faster build by tweaking the solution provided by @uvNikita : 
```nix
    yarnPreBuild = ''
      mkdir -p $HOME/.node-gyp/${nodejs.version}
      echo 9 > $HOME/.node-gyp/${nodejs.version}/installVersion
      ln -sfv ${nodejs}/include $HOME/.node-gyp/${nodejs.version}
    '';
    pkgConfig = {
      node-sass = {
        buildInputs = [ pkgs.python pkgs.libsass pkgs.pkgconfig];
        postInstall = ''
          LIBSASS_EXT=auto yarn --offline run build
          rm build/config.gypi
        '';
      };
    };
```

This solution uses a packaged `libsass` instead of compiling the one included in `node-sass` sources. The main drawback is that it's not guaranteed to be the same version.

Edit: posted too fast

**Comment by uvNikita** [comment]
@jfraudeau of course, this makes sense! Thanks for sharing!
